config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/tasks', to: 'tasks#tasks'
  get 'tasks/new', to: 'tasks#new', as: :task_new
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy'
  get '/tasks/:id', to: 'tasks#find', as: :task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_task, only: [:find, :edit, :update, :destroy]

  def tasks
    @tasks = Task.all
  end

  def find; end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path(@task)
  end

  def edit; end

  def update
    @task.update(task_params)
    @task.save
    redirect_to tasks_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path(@task)
  end

  private

  def find_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/e1f053a175.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title %>
      <%= f.label :details %>
      <%= f.text_field :details %>
      <%= f.label :mark_as_completed %>
      <%= f.check_box :completed %>
      <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<div class="container">
  <h1>Edit your task</h1>
  <%= render 'form' %>
</div>

app/views/tasks/find.html.erb
<div class="container">
  <h1><%= @task.title %></h1>

  <% if @task.completed == false  %>
    <i class="far fa-square"></i>&nbsp &nbsp<%= @task.details %>
  <% else %>
    <i class="far fa-check-square"></i>&nbsp &nbsp<%= @task.details %>
  <% end %>

  <br>
  <br>

  <%= link_to 'Update task', edit_task_path, :class => "btn btn-secondary mt-1 mb-1" %>
  <br>
  <%= link_to 'Back to tasks', tasks_path, :class => "btn btn-secondary mt-1 mb-1" %>
  <br>
  <%= link_to 'Delete task', task_path(@task), method: :delete, data: {confirm: 'Are you sure?'}, :class => "btn btn-secondary mt-1 mb-1" %>
</div>

app/views/tasks/new.html.erb
<div class="container">
  <h1>Create a new task</h1>
  <%= render 'form' %>
</div>

app/views/tasks/tasks.html.erb
<div class="container">
  <h1>My tasks</h1>

  <%= link_to 'Create new task', task_new_path, :class => "btn btn-secondary mt-3 mb-3"%>

  <ul>
    <% @tasks.each do |task| %>
      <% if task.completed == false  %>
        <li class="bg-secondary"><i class="far fa-square"></i>&nbsp &nbsp<%= link_to task.title, task_path(task.id), :class => "text-white" %></li>
      <% else %>
        <li class="bg-secondary"><i class="far fa-check-square"></i>&nbsp &nbsp<%= link_to task.title, task_path(task.id), :class => "text-white" %></li>
      <% end %>
    <% end %>
  </ul>
</div>